### ISSUE TITLE
add example for finding perceived lightness

### ISSUE THREAD

**Issue by listx** [lehins/Color#13]
Hello, I am trying to find out if this library can already do the computation to find perceived lightness as described in [this post](https://stackoverflow.com/a/56678483/437583). If I have a `(Word8, Word8, Word8)` RGB triple, how can I determine perceived lightness using this library? I assume this is possible, but can someone help?

**Comment by lehins** [comment]
Normally I'd suggest either using [gitter](https://gitter.im/haskell-massiv/Lobby) or StackOverflow for questions like this. However in this case, I do agree that it would be nice to add some examples to documentation. So I've created #14 that adds this example to `README.md`. Please, give it a review and make some suggestions if something is not clear.

**Comment by listx** [comment]
I've done a brief read-through of #14 and it looks fantastic! While I haven't had time to actually try out those examples, I assume they are correct. Feel free to close this issue.
