### ISSUE TITLE
Add Lab support

### ISSUE THREAD

**Issue by hyiltiz** [lehins/Color#3]
For the Lab color space.

**Comment by lehins** [comment]
@hyiltiz If you are talking about [CIE L*a*b*](https://en.wikipedia.org/wiki/CIELAB_color_space) color space than it is already implemented in: [`Graphics.Color.Space.CIE1976.LAB`](https://hackage.haskell.org/package/Color-0.2.0/docs/Graphics-Color-Space-CIE1976-LAB.html#t:LAB)

Feel free to re-open the ticket if I misunderstood you somehow.

**Comment by hyiltiz** [comment]
Oh I must have missed that while reading the docs. Thanks!
