### ISSUE TITLE
Add CIELUV, LCh(ab), LCh(uv) colorspaces

### ISSUE THREAD

**Issue by gilgamec** [lehins/Color#4]
This is a request for adding the CIELUV colorspace, as well as the cylindrical views of LAB and LUV, LCh(ab) and LCh(uv).

I'd do this myself and make a PR, but I see that the modules for (most of) these are there, commented out, in the cabal file, and didn't want to duplicate work or clumsily trample tricky problems you had with implementation.

**Comment by lehins** [comment]
Yeah, commented out modules in the cabal file are just placeholders. I haven't really started on those yet, so if you feel like submitting a PR that be great. I am not sure how soon I'd be able to start on those myself.
