### ISSUE TITLE
Add SVG named colours

### ISSUE THREAD

**Issue by AshleyYakeley** [lehins/Color#7]
[SVG defines a set of named colours](https://www.w3.org/TR/SVG11/types.html#ColorKeywords), I believe in sRGB, that are also used in CSS. It would be nice to have these (maybe as `Graphics.Color.Standard.SVG`).

**Comment by lehins** [comment]
100% agree. This was always on my mental TODO list.
If anyone is willing to submit a PR I would certainly be happy to merge it, otherwise I will get to it myself at some point in hopefully not so distant future.
